### ISSUE TITLE
System data statistics

### ISSUE THREAD

**Issue by mfinotti** [kairostech-sw/kairoshub#7]
# System data statistics (step 1/2)
Il sistema storicizza attraverso la piattaforma **_systemmonitor_** i valori di alcuni parametri di sistema, la storicizzazione dei dati avviene ogni 30 secondi. In questo task è necessario aggiungere dei sensori appositi della piattaforma _statistics_  che fungeranno da aggregatori per il calcolo di alcune metriche, nel nostro caso la media. 
Una volta impostati gli aggregatori è necessario aggiungere una automazione basata sul tempo che ogni 30 minuti lancia il seguente evento  `AD_SYSTEM_METRICS`

**Task da completare:**
- [x] Identificare i parametri di sistema
- [x]  Impostare le statistics
- [x]  Automazione system data statistics
- [x] Step 2

## Identificare i parametri di sistema
I parametri di sistema che bisogna tenere sotto controllo sono: 
- type: disk_use_percent
- type: memory_use_percent
- type: processor_use
- type: processor_temperature
- type: last_boot

> rimuovere eventuali altri parametri

## Impostare le statistics
Per ogni sensore è necessario impostare un sensore statistico come nell'esempio seguente: 
`- platform: statistics
    name: "Bathroom humidity mean over last 24 hours"
    entity_id: sensor.bathroom_humidity
    state_characteristic: mean
    max_age:
      minutes: 30`

## Automazione system data statistics
Impostare una automazione basata sul tempo che ogni 30 minuti (stesso tempo del lifetime delle statistiche) che lancia il seguente evento:  `AD_SYSTEM_METRICS`

## Step 2 
[vai allo step 2](https://github.com/kairostech-sw/kairoshub-configuration/issues/6)

**Comment by mfinotti** [comment]
A seguito della verifica effettuata sul kairoshub eccorre rivedere alcuni parametri come di seguito: 

**Sampling size**
- disk_use_percent OK
- memory_use_percent OK
- processor_use --> sampling_size: 75
- processor_temperature --> sampling_side: 100
- last_boot OK

**Comment by mfinotti** [comment]
Rimuovere in fondo al file `configuration.yaml` l'invocazione dello script `run_system_metrics_collect` in quanto non superata e non più necessaria.
